### ISSUE TITLE
Suggestion: Switch the orginal package path from com.xiaomi.mone.* to org.apache.ozhera.*

### ISSUE THREAD

**Issue by HawickMason** [apache/ozhera#457]
Since the entire project is now incubating in Apache, it might be more comprehensive and intuative to use a form package path instead of the orginal. A reasonable candidate would be to replace "com.xiaomi.mone.*" with "org.apache.ozhera.*".

**Comment by psxjoy** [comment]
I think this is a solid suggestion. I've worked on similar tasks before, so feel free to assign this issue to me if possible. @wtt40122 @wodiwudi @gaoxh @sadadw1 
我认为这个是很合理的建议。我之前做过类似的任务，如果可以的话，这个issue可以分派给我。

**Comment by goodjava** [comment]
I am here to modify the ozhera-log module.

**Comment by psxjoy** [comment]
I will modify `ozhera-intelligence` module first.

**Comment by goodjava** [comment]
I am here to modify the ozhera-monitor module.

**Comment by shanwb** [comment]
I will modify ozhera-operator module

**Comment by goodjava** [comment]
I am here to modify the ozhera-prometheus-agent module.

**Comment by shanwb** [comment]
i will modify ozhera-tspandata、ozhera-webhook module

**Comment by goodjava** [comment]
I am here to modify the trace-etl module.

**Comment by goodjava** [comment]
I am here to modify the prometheus-starter-all module.
