### ISSUE TITLE
Suggestion: set reasonable and necessary contribution guidelines

### ISSUE THREAD

**Issue by psxjoy** [apache/ozhera#483]
To maintain the code quality and overall maintainability of the Ozhera project, we need to establish clear guidelines for code contributions. 
A solid coding style and consistent formatting checks are vital for any open-source initiative. 
I suggest we create the following documentation to assist new contributors: 
1. A thorough coding style and formatting specification, including codestyle and checkstyle; 
2. A clear and accurate process for code updates and submitting PRs; 
3. A detailed procedure for reporting vulnerabilities and bugs; 
4. Comprehensive guidelines for unit testing; 
5. Issues should feature tags like `good first issue` to foster greater engagement. 

Moreover, I believe we should work on enhancing community activity. Thus, we should also consider developing a set of rules for incentivizing contributor transitions (from contributor to committer, ultimately to PPMC member) in line with ASF standards.

**Comment by psxjoy** [comment]
Here are some project links that I believe have comprehensive documentation. I welcome any discussions: 
1. [Apache HertzBeat (Incubating)](https://hertzbeat.apache.org/zh-cn/docs/community/contribution) 
2. [Apache Dubbo](https://cn.dubbo.apache.org/zh-cn/contact/) 
3. [Alibaba/Nacos](https://github.com/alibaba/nacos/blob/develop/CONTRIBUTING.md) 
4. [Apache Seata (incubating)](https://seata.apache.org/zh-cn/docs/developers/contributor-guide/new-contributor-guide_dev) 
5. [Alibaba/higress](https://github.com/alibaba/higress/blob/main/CONTRIBUTING_CN.md)

**Comment by psxjoy** [comment]
We should discuss the topic of contributor titles (this doesn't imply any privilege; every contributor should be treated equally and independently).

In an Apache incubating project, the basic roles typically include contributor, committer, and PPMC member, with each role corresponding to an increasing level of responsibility for the project.

We need to establish clear criteria for measuring contributor contributions. What level of involvement is required for someone to become a committer or a PPMC member?

There are currently two common approaches: 
- The first involves assessing the duration and activity level of open-source contributions, which is the most widely used method; 
- The second creates a quantitative score based on the difficulty of issues, allowing discussions about becoming a committer once a certain score is reached.

I'm uncertain if the second method complies with ASF standards.

**Comment by psxjoy** [comment]
BTW, I believe setting a regular time (e.g., once a month or every two weeks) for an online video meeting to discuss project progress and any pressing issues is a good approach (in fact, many projects follow this practice).

**Comment by gaoxh** [comment]
Complete documentation and clear guidance processes are the necessary foundation for a project to continue to grow healthily, and are also the necessary prerequisites for guiding contributors to participate in the project. This is what we urgently need to improve at this stage. We will give high priority to supplementing this content in the future, and we sincerely invite you to join our construction process.

**Comment by psxjoy** [comment]
> Complete documentation and clear guidance processes are the necessary foundation for a project to continue to grow healthily, and are also the necessary prerequisites for guiding contributors to participate in the project. This is what we urgently need to improve at this stage. We will give high priority to supplementing this content in the future, and we sincerely invite you to join our construction process.

Great to see the project moving forward. 
I’d be happy to join and contribute as much as possible.
