### ISSUE TITLE
[fix]  Fix some typos in the project

### ISSUE THREAD

**Issue by psxjoy** [apache/ozhera#486]
While working with the project, I noticed a few spelling errors. 
Would anyone be up for submitting a PR?
If not, I’ll find some time to handle it.

**Comment by psxjoy** [comment]
I believe this should be marked as a `good first issue`,
so any developer interested in contributing can collaborate on resolving it.

**Comment by wtt40122** [comment]
> I believe this should be marked as a `good first issue`,我相信这应该被标记为一个`good first issue` ， so any developer interested in contributing can collaborate on resolving it.因此任何有兴趣做出贡献的开发人员都可以合作解决这个问题。

Can you give some examples

**Comment by psxjoy** [comment]
> > I believe this should be marked as a `good first issue`,我相信这应该被标记为一个`good first issue` ， so any developer interested in contributing can collaborate on resolving it.因此任何有兴趣做出贡献的开发人员都可以合作解决这个问题。
> 
> Can you give some examples

Just a example, in this class [ozhera-app/app-server/src/main/java/org/apache/ozhera/app/config/DataSourceConfig.java](https://github.com/apache/ozhera/blob/master/ozhera-app/app-server/src/main/java/org/apache/ozhera/app/config/DataSourceConfig.java),we have a method
```JAVA
    private void setDatasouce(ComboPooledDataSource dataSource) {
        dataSource.setTestConnectionOnCheckin(true);
        dataSource.setTestConnectionOnCheckout(false);
        dataSource.setPreferredTestQuery("select 1");
        dataSource.setIdleConnectionTestPeriod(180);
    }
```
maybe we can fix `setDatasouce` to `setDatasource`？
It is a little typo mistake, but for beginners，I think maybe a good chance join the ozhera's contribution.
